### ISSUE TITLE
NEP29 flag

### ISSUE THREAD

**Issue by clbarnes** [mimre25/python-eol#1]
Numpy has a more aggressive python deprecation policy the python org, and the scientific/data community tends to follow whatever numpy does. For that reason, it would be useful to have a `--nep29` (or `--numpy`) flag, simply because this policy affects such a large proportion of python developers (especially professionals).

Here is numpy's doc page about it: https://numpy.org/neps/nep-0029-deprecation_policy.html#support-table

**Comment by mimre25** [comment]
As mentioned on reddit - I like the idea :+1: 

Do you happen to have an idea if the support table is somewhere available in machine readable format? That would ease the process of keeping it up to date.

**Comment by clbarnes** [comment]
On that page, either the support table or drop schedule look pretty parseable. Could keep a script in the repo outside of the package which updates the database and writes it into the package for the next release.

Alternatively, you could do something like [tealdeer](https://github.com/dbrgn/tealdeer), which manages its own cache so you don't need to update the tool to update the deprecation schedule. That would look like:

- use [appdirs](https://pypi.org/project/appdirs/) to find the user cache directory
- write your database(s) there, along with a file with the timestamp of the last update
- on execution, if the database is more than X days old (or absent), give the user a warning recommending they do e.g. `eol --update` (or just update automatically)
- `eol --update` fetches the latest schedule from the endoflife.date API and NEP29 page respectively
 
More complicated upfront but it drastically reduces your maintenance burden going forward, and means users don't need to update regularly.

**Comment by mimre25** [comment]
I like your suggestion with the caching on the user end - I think this will be definitely the way to go in the long run.

For now I've added the nep mode just with a static db. - Please check the PR if that's what you wanted (just double checking), and then I'd cut a release.
